#!/bin/bash

# run from parent cwd

cur_dir=$(pwd)

rm ./logs/*.log
rm ./output/*.rul ./output/*.yaml
python3 ./yammler/yammler.py ~/Games/openxcom/user/mods/ROSIGMA ~/Games/openxcom/user/mods/OXCE_40k

cd output
bash sorter.sh

echo "Autogenerated by yammler with ROSIGMA and OXCE_40k as arguments" > readme.txt
echo "Last ran: $(date)"

cd $cur_dir
rm ./logs/*.log
rm ./output/*.rul ./output/*.yaml